[versions]
kotlin = "1.5.10"

android-compile = "30"
android-target = "30"
android-min = "21"

android-gradle = "7.1.0-alpha03"
date-time = "0.2.1"

accompanist = "0.14.0"

androidx-appCompat = "1.4.0-alpha02"
androidx-compose = "1.0.0-rc02"
androidx-constraintlayout = "1.0.0-alpha08"
androidx-activity = "1.3.0-beta01"
androidx-navigation = "2.4.0-alpha02"
androidx-lifecycle = "2.4.0-alpha01"
androidx-palette = "1.0.0"

coil = "1.3.0"
coroutines = "1.5.0"
glide = "4.11.0"
hilt = "2.37"
hiltNavigation = "1.0.0-alpha02"
kenburns = "1.0.7"
ktor = "1.6.0"
material = "1.4.0-beta01"
napier = "1.5.0"
squareup-leakcanary = "2.7"
sqldelight = "1.5.0"
turbine = "0.5.2"

testing-arch-core = "2.1.0"
testing-assertK = "0.24"
testing-junit = "4.13.2"
testing-junitext = "1.1.3-beta02"
testing-junit5 = "5.8.0-M1"
testing-kotest = "4.6.0"
testing-mockk = "1.12.0"
testing-mockito-core = "3.11.1"
testing-mockito-kotlin = "2.2.0"
testing-opentest = "1.1.1"

plugins-buildkonfig = "0.7.0"
plugins-gradle-versions = "0.39.0"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "date-time" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }

androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose" }
androidx-compose-ui-runtime = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose" }
androidx-compose-runtime-core = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }

glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
material = { module = "com.google.android.material:material", version.ref = "material" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kenburns = { module = "com.flaviofaria:kenburnsview", version.ref = "kenburns" }

squareup-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareup-leakcanary" }
squareup-sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }
squareup-sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
squareup-sqldelight-driver-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
squareup-sqldelight-driver-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }

plugins-dependency-check = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "plugins-gradle-versions" }
plugins-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugins-buildkonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "plugins-buildkonfig" }
plugin-squareup-sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }

testing-androidx-core = { module = "androidx.arch.core:core-testing", version.ref = "testing-arch-core" }
testing-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "testing-junitext" }
testing-androidx-junitktx = { module = "androidx.test.ext:junit-ktx", version.ref = "testing-junitext" }

testing-junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "testing-junit5" }
testing-junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "testing-junit5" }
testing-junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "testing-junit5" }
testing-junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "testing-junit5" }

testing-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "testing-kotest" }
testing-kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "testing-kotest" }

testing-mockk-core = { module = "io.mockk:mockk", version.ref = "testing-mockk" }
testing-mockk-common = { module = "io.mockk:mockk-common", version.ref = "testing-mockk" }

testing-assertK = { module = "com.willowtreeapps.assertk:assertk", version.ref = "testing-assertK" }
testing-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
testing-junit = { module = "junit:junit", version.ref = "testing-junit" }
testing-opentest = { module = "org.opentest4j:opentest4j", version.ref = "testing-opentest" }
testing-mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "testing-mockito-core" }
testing-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

testing-ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
