[versions]
kotlin = "1.5.31"

android-compile = "31"
android-target = "31"
android-min = "21"

android-gradle = "7.1.0-beta04"
date-time = "0.3.1"

accompanist = "0.21.3-beta"
snapper = "0.1.0"

androidx-activity = "1.4.0"
androidx-appCompat = "1.4.0"
androidx-compose = "1.1.0-beta03"
androidx-composePaging = "1.0.0-alpha14"
androidx-constraintlayout = "1.0.0-rc02"
androidx-lifecycle = "2.4.0"
androidx-navigation = "2.4.0-beta02"
androidx-palette = "1.0.0"
androidx-paging = "3.1.0"

coil = "1.4.0"
coroutines-native = "1.5.2-native-mt"
desugar = "1.1.5"
hilt = "2.40.2"
hiltNavigation = "1.0.0-beta01"
kenburns = "1.0.7"
ktor = "1.6.5"
material = "1.5.0-beta01"
multiplatform-paging = "0.4.5"
napier = "1.5.0"
squareup-leakcanary = "2.7"
sqldelight = "1.5.3"
turbine = "0.7.0"

testing-arch-core = "2.1.0"
testing-junit = "4.13.2"
testing-junitext = "1.1.4-alpha03"
testing-junit5 = "5.8.1"
testing-kotest = "5.0.0.M2"
testing-mockk = "1.12.1"
testing-mockito-core = "3.12.4"
testing-mockito-kotlin = "2.2.0"

plugin-buildkonfig = "0.7.0"
plugin-gradle-versions = "0.39.0"
plugin-kmp-native-coroutines = "0.8.0"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "android-gradle" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "date-time" }

kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines-native" }

accompanist-pager-core = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicator = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-insets = { module = "com.google.accompanist:accompanist-insets", version.ref = "accompanist" }
accompanist-insetsui = { module = "com.google.accompanist:accompanist-insets-ui", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }

androidx-appCompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appCompat" }
androidx-palette = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette" }

androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "androidx-compose" }
androidx-compose-ui-runtime = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose" }
androidx-compose-runtime-core = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose" }
androidx-compose-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "androidx-constraintlayout" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
androidx-compose-paging = { module = "androidx.paging:paging-compose", version.ref = "androidx-composePaging" }

androidx-lifecycle-compiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }

androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "androidx-paging" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-navigation = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigation" }

ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

coil = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
desugar = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar" }
material = { module = "com.google.android.material:material", version.ref = "material" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kenburns = { module = "com.flaviofaria:kenburnsview", version.ref = "kenburns" }
snapper = { module = "dev.chrisbanes.snapper:snapper", version.ref = "snapper" }

multiplatform-paging-core = { module = "io.github.kuuuurt:multiplatform-paging", version.ref = "multiplatform-paging" }
multiplatform-paging-ios-x64 = { module = "io.github.kuuuurt:multiplatform-paging-iosX64", version.ref = "multiplatform-paging" }
multiplatform-paging-ios-arm64 = { module = "io.github.kuuuurt:multiplatform-paging-iosArm64", version.ref = "multiplatform-paging" }

squareup-leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "squareup-leakcanary" }
squareup-sqldelight-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
squareup-sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }
squareup-sqldelight-driver-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
squareup-sqldelight-driver-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
squareup-sqldelight-driver-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }

plugin-dependency-check = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "plugin-gradle-versions" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugin-buildkonfig = { module = "com.codingfeline.buildkonfig:buildkonfig-gradle-plugin", version.ref = "plugin-buildkonfig" }
plugin-squareup-sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
plugin-kmp-native-coroutines = { module = "com.rickclephas.kmp:kmp-nativecoroutines-gradle-plugin", version.ref = "plugin-kmp-native-coroutines" }

testing-androidx-core = { module = "androidx.arch.core:core-testing", version.ref = "testing-arch-core" }
testing-androidx-junit = { module = "androidx.test.ext:junit", version.ref = "testing-junitext" }

testing-junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "testing-junit5" }
testing-junit5-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "testing-junit5" }
testing-junit5-vintage = { module = "org.junit.vintage:junit-vintage-engine", version.ref = "testing-junit5" }

testing-kotest-assertions = { module = "io.kotest:kotest-assertions-core", version.ref = "testing-kotest" }
testing-kotest-runner = { module = "io.kotest:kotest-runner-junit5", version.ref = "testing-kotest" }

testing-mockk-core = { module = "io.mockk:mockk", version.ref = "testing-mockk" }
testing-mockk-common = { module = "io.mockk:mockk-common", version.ref = "testing-mockk" }

testing-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-native" }
testing-junit = { module = "junit:junit", version.ref = "testing-junit" }
testing-mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "testing-mockito-core" }
testing-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

testing-ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
