name: "Android Build Check"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      TMDB_API_URL: ${{ secrets.TMDB_API_URL }}

    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/checkout@v2

      - name: Add App Secrets
        run: |
            echo -e "\TMDB_API_KEY=$TMDB_API_KEY" >> ./local.properties
            echo -e "\TMDB_API_URL=$TMDB_API_URL" >> ./local.properties

      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleDebug

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs