name: "Android Build Check"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      TMDB_API_URL: ${{ secrets.TMDB_API_URL }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Generate build number
        shell: bash
        run: echo "BUILD_NUMBER=$(( $GITHUB_RUN_NUMBER + 6000 + (($GITHUB_RUN_NUMBER - 980) * 3) ))" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Add App Secrets
        run: |
          echo -e "\TMDB_API_KEY=$TMDB_API_KEY" >> ./local.properties
          echo -e "\TMDB_API_URL=$TMDB_API_URL" >> ./local.properties

      - uses: burrunan/gradle-cache-action@v1
        name: Build and check
        env:
          ORG_GRADLE_PROJECT_TVMANIAC_VERSIONCODE: ${{ env.BUILD_NUMBER }}
        with:
          gradle-dependencies-cache-key: |
            gradle/libs.versions.toml
          arguments: |
            bundle
            testDebugUnitTest
            assembleDebug

      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build outputs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: build-outputs
          path: app/build/outputs