name: "Share build & Unit test"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

  fields_setup:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  test:
    needs: fields_setup
    name: Run all Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Add App Secrets
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_API_URL: ${{ secrets.TMDB_API_URL }}
        run: |
            echo -e "\TMDB_API_KEY=$TMDB_API_KEY" >> ./local.properties
            echo -e "\TMDB_API_URL=$TMDB_API_URL" >> ./local.properties

      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Unit Tests
        run: ./gradlew testDebugUnitTest