name: "Publish swift package"

on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Add App Secrets
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_API_URL: ${{ secrets.TMDB_API_URL }}
        run: |
          echo -e "\TMDB_API_KEY=$TMDB_API_KEY" >> ./local.properties
          echo -e "\TMDB_API_URL=$TMDB_API_URL" >> ./local.properties
      - name: Build iOS framework
        id: buildPackage
        run: ./gradlew createSwiftPackage
      - name: Upload Swift Package directory
        uses: actions/upload-artifact@v2
        with:
          name: swiftpackage
          path: shared/swiftpackage
          retention-days: 1

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download directory with swift package
        uses: actions/download-artifact@v2
        with:
          name: swiftpackage
          path: swiftpackage
      - name: Create tag
        uses: actions/github-script@v5
        id: tag-creation
        with:
          github-token: ${{ secrets.API_TOKEN_GITHUB }}
          script: |
            const { repo: { owner, repo }, sha } = context;
            const tag = process.env.GITHUB_REF.split('/').slice(-1)[0];
            const release = await github.repos.createRelease({
                owner, repo,
                tag_name: tag ,
                prerelease: true
            });
            console.log(`Result ${tag} ${release}`)
            result-encoding: tag
      - name: Access tag name of current workflow
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.GITHUB_ENV }}
          echo "${{steps.tag-creation.outputs.result}}"
      - name: Create release branch on package repo
        uses: GuillaumeFalourd/create-other-repo-branch-action@v1
        with:
          repository_owner: c0de-wizard
          repository_name: tvmaniac-swift-packages
          new_branch_name: ${{ env.GITHUB_ENV }}
          access_token: ${{ secrets.API_TOKEN_GITHUB}}
      - name: Push directory to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'swiftpackage'
          destination-github-username: 'c0de-wizard'
          destination-repository-name: 'tvmaniac-swift-packages'
          user-email: kioko.publish@gmail.com
          target-branch: ${{ env.GITHUB_ENV }}
