name: "Share build & Unit test"

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    paths:
      - 'shared/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

  fields_setup:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  test:
    needs: fields_setup
    name: Run all Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build with Gradle
        run: ./gradlew build

      - name: Unit Tests
        run: bash ./gradlew testDebugUnitTest